# Generated by Django 5.1 on 2024-10-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_start_time', models.DateTimeField(blank=True, help_text='Время старта процесса', null=True, verbose_name='Старт')),
                ('process_end_time', models.DateTimeField(blank=True, help_text='Время окончания процесса (если процесс завершен)', null=True, verbose_name='Завершение')),
                ('process_take_time', models.DurationField(blank=True, help_text='Сколько всего времени заняло исполнение процесса (если процесс завершен)', null=True, verbose_name='Время выполнения')),
                ('process_ended', models.BooleanField(default=False, help_text='True или False. Если True - значит процесс завершен, если False - значит процесс все еще в работе', verbose_name='Статус')),
                ('process_error', models.TextField(blank=True, help_text='Ошибка при выполнении процесса (если возникла)', null=True, verbose_name='Ошибка')),
                ('process_error_traceback', models.TextField(blank=True, help_text='Трейсбэк ошибки (если возникла ошибка)', null=True, verbose_name='Трейсбэк')),
                ('process_backend_id', models.CharField(help_text='Уникальный идентификатор процесса, созданный на бэкенде', max_length=254, unique=True, verbose_name='id процесса')),
                ('process_started', models.BooleanField(default='', help_text='Если процесс запущен - True, если нет - False.', verbose_name='Запуск процесса')),
                ('source_img', models.ImageField(blank=True, null=True, upload_to='upload_user_photo/', verbose_name='Загруженное изображение пользователя')),
                ('target_img', models.ImageField(blank=True, null=True, upload_to='upload_user_photo/', verbose_name='Загруженное изображение на кого накладывать')),
                ('output_img', models.ImageField(blank=True, null=True, upload_to='upload_user_photo/', verbose_name='Путь, куда надо сгружать')),
                ('maximum_number_processes', models.CharField(blank=True, help_text='Максимальное кол-во процессов', max_length=10, null=True, verbose_name='Кол-во процессов')),
                ('task_id', models.IntegerField(blank=True, help_text='Номер task', null=True, verbose_name='task_id')),
                ('inswapper_config_upscale', models.IntegerField(blank=True, help_text='default=8', null=True, verbose_name='upscale')),
                ('inswapper_config_codeformer_fidelity', models.FloatField(blank=True, help_text='default=0.90', null=True, verbose_name='codeformer_fidelity')),
            ],
            options={
                'verbose_name': 'Процесс',
                'verbose_name_plural': 'Процессы',
            },
        ),
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название сервера')),
                ('auth_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Настройка сервера',
                'verbose_name_plural': 'Настройка сервера',
            },
        ),
    ]
